{
  "name": "my-web-app",
  "version": "1.0.0",
  "main": "app.js",
  "scripts": {
    "start": "node app.js",
    "test": "echo \"No tests yet\" && exit 0"
  }
}
Ravindranadh Tagore Karanapu
10:53 AM
const http = require('http');
const port = 3000;

const server = http.createServer((req, res) => {
  res.end('Hello from GitHub Actions CI/CD pipeline!');
});

server.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
});
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t my-web-app .

    -
